"""Parse LKK 用字表 CSV into hanlo_rules.yaml.

Determines which words should output as Han characters vs romanization
in mixed Han-Lo writing, following LKK (李江却基金會) standards.
"""

import argparse
import csv
import sys
import unicodedata
from pathlib import Path
from typing import TextIO

import yaml


def _has_cjk(text: str) -> bool:
    """Check if text contains any CJK ideograph characters."""
    return any(unicodedata.category(ch).startswith("Lo") for ch in text)


def classify_hanlo_type(suggested_word: str) -> str:
    """Classify a word as 'han' (output Han characters) or 'lo' (output romanization).

    Args:
        suggested_word: The 建議用字 field from LKK table

    Returns:
        "han" if word contains CJK characters, "lo" otherwise
    """
    if _has_cjk(suggested_word):
        return "han"
    return "lo"


def parse_lkk_csv(csvfile: TextIO) -> list[dict]:
    """Parse LKK 用字表 CSV into structured rules.

    Args:
        csvfile: File-like object containing tab-separated LKK CSV

    Returns:
        List of dicts with keys: word, type (han/lo), kip, hoabun
    """
    rules = []
    # LKK CSV uses comma delimiter (downloaded from Google Sheets)
    # Sniff the dialect to auto-detect
    sample = csvfile.read(1024)
    csvfile.seek(0)
    delimiter = "\t" if "\t" in sample else ","
    reader = csv.DictReader(csvfile, delimiter=delimiter)
    for row in reader:
        word = row.get("建議用字", "").strip()
        kip_numeric = row.get("數字版音讀", "").strip()
        kip_unicode = row.get("音讀", "").strip()
        hoabun = row.get("對應華語", "").strip()
        if not word:
            continue
        rules.append(
            {
                "word": word,
                "type": classify_hanlo_type(word),
                "kip": kip_numeric or kip_unicode,
                "hoabun": hoabun,
            }
        )
    return rules


def write_hanlo_rules_yaml(rules: list[dict], output_path: Path) -> None:
    """Write hanlo classification rules to YAML.

    Args:
        rules: List of rule dicts
        output_path: Path to write hanlo_rules.yaml
    """
    data = {}
    for rule in rules:
        word = rule["word"]
        data[word] = {
            "type": rule["type"],
            "kip": rule["kip"],
            "hoabun": rule["hoabun"],
        }
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("# hanlo_rules.yaml — LKK 漢羅分類表\n")
        f.write("# type: han = 輸出漢字, lo = 輸出羅馬字\n")
        f.write("# Generated by scripts/parse_lkk_rules.py\n\n")
        yaml.dump(data, f, allow_unicode=True, default_flow_style=False, sort_keys=False)


def main(argv: list[str] | None = None) -> None:
    """CLI entry point for LKK rules parsing."""
    parser = argparse.ArgumentParser(description="Parse LKK CSV to hanlo_rules.yaml")
    parser.add_argument("--input", type=Path, required=True, help="Path to lkk_yongji.csv")
    parser.add_argument("--output", type=Path, required=True, help="Output path for hanlo_rules.yaml")
    args = parser.parse_args(argv)

    if not args.input.exists():
        print(f"Error: Input file not found: {args.input}", file=sys.stderr)
        sys.exit(1)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    with open(args.input, encoding="utf-8") as f:
        rules = parse_lkk_csv(f)
    write_hanlo_rules_yaml(rules, args.output)
    print(f"Written {len(rules)} rules to {args.output}")


if __name__ == "__main__":
    main()
